name: First workflow

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Building stage

    steps:
      - name: Collect the code
        uses: actions/checkout@v4
      - name: Installing dependencies
        run: npm ci
      - name: Lint
        run: npm run lint


#  testing:
#
#  deploy: