name: First workflow

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Building stage
    outputs:
      output: ${{ steps.message.outputs.something }}

    steps:
      - name: Collect the code
        uses: actions/checkout@v4
      - name: cashing step
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Installing dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: message
        run: echo "something=Hello World" >> "$GITHUB_OUTPUT"


  testing:
    runs-on: ubuntu-latest
    name: Testing Stage
    needs: build

    steps:
      - name: collect the code
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: install dependencies
        run: npm ci
      - name: Test output from build
        run: echo "${{ needs.build.outputs.output }}"
      - name: Testing the code
        run: npm run test

      #  deploy: