name: First workflow

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Building stage

    steps:
      - name: Collect the code
        uses: actions/checkout@v4
      - name: Installing dependencies
        run: npm ci
      - name: Lint
        run: npm run lint


  testing:
    runs-on: ubuntu-latest
    name: Testing Stage
    needs: build

    steps:
      - name: collect the code
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
      - name: install dependencies
        run: npm ci
      - name: Testing the code
        run: npm run test

      #  deploy: